const types = {
    GET_ITEMS: 'GET_ITEMS',
    ADD_ITEM: 'ADD_ITEM',
    DELETE_ITEM: 'DELETE_ITEM',
    ITEM_FETCHING: 'ITEM_FETCHING',
    ERROR_FETCHING: 'ERROR_FETCHING',
    LOGIN: 'LOGIN',
    REGISTER_USER: 'REGISTER_USER',
    USER_FETCHING: 'USER_FETCHING',
    GET_CURRENT_USER: 'GET_CURRENT_USER',
    USER_ERROR_FETCHING: 'USER_ERROR_FETCHING',

}

export default types;